# Generated by Django 2.1.5 on 2019-01-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malnutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/Images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(help_text='Enter Your Firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Enter your height by cm', max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(help_text='Enter Your Lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Enter Password', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Enter Username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Enter your weight by kg', max_digits=20),
        ),
    ]
