# Generated by Django 2.1.5 on 2019-01-29 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malnutrition', '0002_auto_20190126_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(help_text='Enter Your Firstname', max_length=100)),
                ('lastname', models.CharField(help_text='Enter Your Lastname', max_length=100)),
                ('birthdate', models.DateField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter your weight by kg', max_digits=20)),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter your height by cm', max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
