# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malnutrition', '0003_auto_20190129_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
