# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malnutrition', '0005_appuser_physicalactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='physicalactivity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
