# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malnutrition', '0006_auto_20190206_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='physicalactivity',
        ),
    ]
