# Generated by Django 2.1.7 on 2019-02-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malnutrition', '0007_remove_appuser_physicalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='physical_activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
